POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test name",
    "number": "123456"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "123456"
}